import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

async function prerender() {
  // Import the server entry point
  const { render } = await import('./dist/entry-server.js')
  
  // Read the client HTML template (should be generated by client build)
  const distHtmlPath = path.resolve(__dirname, 'dist/index.html')
  const template = fs.readFileSync(distHtmlPath, 'utf-8')
  
  // Render the app HTML
  const { html } = render()
  
  // Replace the placeholder with the rendered HTML
  let finalHtml = template.replace('<!--app-html-->', html)
  
  // Fix the script reference to point to the hydration entry point
  finalHtml = finalHtml.replace(
    /src="\/src\/main\.tsx"/g,
    'src="/src/entry-client.tsx"'
  ).replace(
    /src="\/assets\/main-[^"]+\.js"/g, 
    'src="/src/entry-client.tsx"'
  )
  
  // Write the prerendered HTML
  fs.writeFileSync(distHtmlPath, finalHtml)
  
  console.log('✅ Prerendered index.html with SSR content')
}

prerender().catch(err => {
  console.error('❌ Prerender failed:', err)
  process.exit(1)
})